### ISSUE TITLE
No control over backlight 

### ISSUE THREAD

**Issue by PaulMagos** [hieplpvip/AppleBacklightSmoother#3] opened 2020-10-07 13:01 UTC
I’m on ASUS Zenbook UX430UNR, OpenCore 0.6.2 from ur repo, and i’ve tried many times but with this kext my backlight doesn’t work. I see the image on screen of the backlight when i press the buttons but the screen remains at the same light level.

**Comment by hieplpvip** [comment] 2020-10-07 15:22
Send me output from https://github.com/hieplpvip/OC-gen-debug

**Comment by PaulMagos** [comment] 2020-10-08 10:21
http://www.mediafire.com/file/kqxylrxc3fa0fuc/debug_14561.zip/file
Thanks.

**Comment by hieplpvip** [comment] 2020-10-08 10:58
Hi, I see that you're injecting wrong `AAPL,ig-platform-id` and `device-id`.

`AAPL,ig-platform-id` should be `0000C087`, while `device-id` should be `16590000`, as done [here](https://github.com/hieplpvip/Asus-Zenbook-Hackintosh/blob/81a6f88ead51622ccbfba092cd6900849baebd3b/src/config/ux430-kabylaker.plist#L650-L662).

If backlight still doesn't work after fixing id, please use DEBUG version and generate new debugging files.

Thanks.

**Comment by PaulMagos** [comment] 2020-10-08 11:29
Tried it yesterday, and the results are the same, anyway I'll try it another time and send file.

**Comment by PaulMagos** [comment] 2020-10-08 11:34
[Here it is](http://www.mediafire.com/file/6yxr14xlfeek4nd/debug_4032.zip/file)

thanks

**Comment by hieplpvip** [comment] 2020-10-08 17:06
Hi, I need some output from DEBUG version. Please add boot-arg `-applbklsmoothdbg` and try this one, then create new debugging files.

[AppleBacklightSmoother-1.0.0-DEBUG.zip](https://github.com/hieplpvip/AppleBacklightSmoother/files/5349613/AppleBacklightSmoother-1.0.0-DEBUG.zip)

In addition, can you try sleeping and see if backlight works after sleep? I know this sounds weird, but I had this problem before, so we should try everything possible.

Thank you a lot!

**Comment by PaulMagos** [comment] 2020-10-08 18:14
I'll try asap, Thanks to you.

**Comment by benbender** [comment] 2020-10-08 22:45
Hey,

thanks for your effort! It doesn't work for me either on Kaby Lake Refresh / UHD 620 / DeviceId 5917 on Big Sur. Used your suggested framebuffer-config and the Debug-version of the kext and got the following output. There are two obvious problems:

- System is KabyLake and not CoffeeLake
- The denied cache read

I don't have any lilucpu-boot-arg or similar in place. Used platform-id is macbookpro14,1. If I can provide any more info, please let me know.

````
[   11.597468]: AppleBacklightSmoother  smoother: @ (DBG) Successfully routed hwSetBacklight
[   12.412805]: AppleBacklightSmoother  smoother: @ (DBG) wrapCflFakeWriteRegister32: system initialized BXT_BLC_PWM_FREQ1 = 0x4240161
[   12.412818]: AppleBacklightSmoother  smoother: @ (DBG) wrapCflFakeWriteRegister32: system initialized BXT_BLC_PWM_CTL1 = 0x80000000
[   12.412826]: AppleBacklightSmoother  smoother: @ (DBG) wrapCflFakeWriteRegister32: write PWM_DUTY1 0x4f5/0x56c, rescaled to 0x3c9203f/0x4240161
[   12.412917]: AppleBacklightSmoother  smoother: @ (DBG) wrapCflFakeWriteRegister32: write PWM_DUTY1 0x4f5/0x56c, rescaled to 0x3c9203f/0x4240161
[   12.412959]: AppleBacklightSmoother  smoother: @ (DBG) wrapCflFakeWriteRegister32: write PWM_DUTY1 0x4f5/0x56c, rescaled to 0x3c9203f/0x4240161
[   12.412971]: AppleBacklightSmoother  smoother: @ (DBG) wrapCflFakeWriteRegister32: write PWM_DUTY1 0x4f5/0x56c, rescaled to 0x3c9203f/0x4240161
[   13.507002]: AppleBacklightSmoother  smoother: @ (DBG) wrapCflFakeWriteRegister32: write PWM_DUTY1 0x4f5/0x56c, rescaled to 0x3c9203f/0x4240161
[   13.535636]: AppleBacklightSmoother  smoother: @ (DBG) wrapCflFakeWriteRegister32: write PWM_DUTY1 0x4f5/0x56c, rescaled to 0x3c9203f/0x4240161
[   13.535650]: AppleBacklightSmoother  smoother: @ (DBG) wrapCflFakeWriteRegister32: write PWM_DUTY1 0x4f5/0x56c, rescaled to 0x3c9203f/0x4240161
[   13.535662]: AppleBacklightSmoother  smoother: @ (DBG) wrapCflFakeWriteRegister32: write PWM_DUTY1 0x4f5/0x56c, rescaled to 0x3c9203f/0x4240161
[   13.535673]: AppleBacklightSmoother  smoother: @ (DBG) wrapCflFakeWriteRegister32: write PWM_DUTY1 0x4f5/0x56c, rescaled to 0x3c9203f/0x4240161
[   13.535688]: AppleBacklightSmoother  smoother: @ (DBG) wrapCflFakeWriteRegister32: write PWM_DUTY1 0x4f5/0x56c, rescaled to 0x3c9203f/0x4240161
[   13.569032]: AppleBacklightSmoother  smoother: @ (DBG) wrapCflFakeWriteRegister32: write PWM_DUTY1 0x4f5/0x56c, rescaled to 0x3c9203f/0x4240161
[   13.569045]: AppleBacklightSmoother  smoother: @ (DBG) wrapCflFakeWriteRegister32: write PWM_DUTY1 0x4f5/0x56c, rescaled to 0x3c9203f/0x4240161
[   13.569057]: AppleBacklightSmoother  smoother: @ (DBG) wrapCflFakeWriteRegister32: write PWM_DUTY1 0x4f5/0x56c, rescaled to 0x3c9203f/0x4240161
[   13.569069]: AppleBacklightSmoother  smoother: @ (DBG) wrapCflFakeWriteRegister32: write PWM_DUTY1 0x4f5/0x56c, rescaled to 0x3c9203f/0x4240161
[   13.569086]: AppleBacklightSmoother  smoother: @ (DBG) wrapCflFakeWriteRegister32: write PWM_DUTY1 0x4f5/0x56c, rescaled to 0x3c9203f/0x4240161
[   13.587073]: AppleBacklightSmoother  smoother: @ (DBG) wrapCflFakeWriteRegister32: write PWM_DUTY1 0x4f5/0x56c, rescaled to 0x3c9203f/0x4240161
[   13.587087]: AppleBacklightSmoother  smoother: @ (DBG) wrapCflFakeWriteRegister32: write PWM_DUTY1 0x4f5/0x56c, rescaled to 0x3c9203f/0x4240161
[   13.587098]: AppleBacklightSmoother  smoother: @ (DBG) wrapCflFakeWriteRegister32: write PWM_DUTY1 0x4f5/0x56c, rescaled to 0x3c9203f/0x4240161
[   13.587109]: AppleBacklightSmoother  smoother: @ (DBG) wrapCflFakeWriteRegister32: write PWM_DUTY1 0x4f5/0x56c, rescaled to 0x3c9203f/0x4240161
[   13.587123]: AppleBacklightSmoother  smoother: @ (DBG) wrapCflFakeWriteRegister32: write PWM_DUTY1 0x4f5/0x56c, rescaled to 0x3c9203f/0x4240161
[   13.782610]: AppleBacklightSmoother  smoother: @ (DBG) wrapCflFakeWriteRegister32: write PWM_DUTY1 0x4f5/0x56c, rescaled to 0x3c9203f/0x4240161
[   13.822815]: AppleBacklightSmoother  smoother: @ (DBG) wrapCflFakeWriteRegister32: write PWM_DUTY1 0x4f5/0x56c, rescaled to 0x3c9203f/0x4240161
[   15.843885]: AppleBacklightSmoother  smoother: @ (DBG) wrapCflFakeWriteRegister32: write PWM_DUTY1 0x4f5/0x56c, rescaled to 0x3c9203f/0x4240161
[   15.893827]: AppleBacklightSmoother  smoother: @ (DBG) wrapCflFakeWriteRegister32: write PWM_DUTY1 0x4f5/0x56c, rescaled to 0x3c9203f/0x4240161
[   22.925979]: AppleBacklightSmoother  smoother: @ (DBG) wrapCflFakeWriteRegister32: write PWM_DUTY1 0x4f5/0x56c, rescaled to 0x3c9203f/0x4240161
[   22.927415]: Sandbox: imagent(354) deny(1) mach-lookup com.apple.system.opendirectoryd.apiAppleBacklightSmoother  smoother: @ (DBG) wrapCflFakeWriteRegister32: write PWM_DUTY1 0x4f5/0x56c, rescaled to 0x3c9203f/0x4240161
[   22.974783]: AppleBacklightSmoother  smoother: @ (DBG) wrapCflFakeWriteRegister32: write PWM_DUTY1 0x4f5/0x56c, rescaled to 0x3c9203f/0x4240161
[   22.991939]: AppleBacklightSmoother  smoother: @ (DBG) wrapCflFakeWriteRegister32: write PWM_DUTY1 0x4f5/0x56c, rescaled to 0x3c9203f/0x4240161
[   23.339852]: Sandbox: routined(298) deny(1) mach-lookup com.apple.Maps.MapsSync.storeSandbox: nsurlsessiond(189) deny(1) file-write-create /private/var/db/nsurlsessiond/LibraryAppleBacklightSmoother  smoother: @ (DBG) wrapCflFakeWriteRegister32: write PWM_DUTY1 0x4f5/0x56c, rescaled to 0x3c9203f/0x4240161
[   24.639980]: Sandbox: AssetCacheLocato(434) deny(1) user-preference-read kCFPreferencesAnyApplicationSandbox: 1 duplicate report for AssetCacheLocato deny(1) user-preference-read kCFPreferencesAnyApplicationSandbox: distnoted(435) deny(1) file-read-metadata /usr/sbin/distnotedSandbox: distnoted(435) deny(1) file-read-metadata /usrSandbox: parsecd(371) deny(1) mach-lookup com.apple.securityd.xpcAppleBacklightSmoother  smoother: @ (DBG) wrapCflFakeWriteRegister32: write PWM_DUTY1 0x4f5/0x56c, rescaled to 0x3c9203f/0x4240161
````

**Comment by hieplpvip** [comment] 2020-10-09 03:54
Seems like CPU is incorrectly recognized as Coffee Lake. Can you try boot-arg `lilucpu=9`?

**Comment by hieplpvip** [comment] 2020-10-09 04:43
I suspect that Lilu is returning incorrect CPU generation. Please post output from this tool. It's based on Lilu CPUID parsing code.

[cpuidparser.zip](https://github.com/hieplpvip/AppleBacklightSmoother/files/5352641/cpuidparser.zip)

**Comment by benbender** [comment] 2020-10-09 06:38
Yeah, you are right:

````
CPU vendor: Intel
CPU max level: 0x16
CPU max level (ext): 0x80000008
CPU brand: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
CPU family: 6
CPU model: 142
CPU stepping: 0xa
CPU generation: 10 (Coffee Lake)
````

Very interesting. will pin to kaby lake and test again later.

**Comment by PaulMagos** [comment] 2020-10-09 06:59
with the argument `lilucpu=9` works, for me

**Comment by benbender** [comment] 2020-10-09 07:00
And it seems to be the intended behavior. See https://github.com/acidanthera/Lilu/blob/3b302dc0d972b8cf89c19569dfbea75a16b3c51a/Lilu/Sources/kern_cpu.cpp#L107

Didn't knew that...

**Comment by hieplpvip** [comment] 2020-10-09 07:02
@benbender Yeah, I have seen that. I'm opening a bug report now. For now please use `lilucpu=9`

**Comment by benbender** [comment] 2020-10-09 07:09
A fine, want to do the same. Btw, old Bug about the same topic for reference: 
https://github.com/acidanthera/bugtracker/issues/290

Thanks again!

**Comment by benbender** [comment] 2020-10-09 07:16
Can confirm that it works with `lilucpu=9`. Issue can be closed I think if a note is added for the moment.

**Comment by hieplpvip** [comment] 2020-10-09 07:22
I'm thinking about doing the CPUID check on our side to determine if it's Kaby Lake-R or Coffee Lake, as it seems from https://github.com/acidanthera/bugtracker/issues/290 that this "bug" is intentional behavior.

It seems that stepping 0x9 is Kaby Lake, 0xa is Kaby Lake-R, 0xb is Coffee Lake.

**Comment by benbender** [comment] 2020-10-09 07:40
Yes, I think so. And that might be ok for the "cpu side" of things, but for lilu and its cpu-detection, on which other projects build upon, its at least a documentation issue. There should be some notes in the code I think to avoid such problems like this one in the first place.

**Comment by PaulMagos** [comment] 2020-10-09 08:09
one more thing, since my brightness works fine without (maybe I don't notice difference) , I don't understand the meaning of this kext, can u explain it to me ?

**Comment by hieplpvip** [comment] 2020-10-09 08:21
It gives you smooth backlight transitions by splitting one big change in brightness into multi consecutive smaller changes.

**Comment by benbender** [comment] 2020-10-09 08:41
I can see the more "smooth" transition clearly. For me its working as intended, I think.

**Comment by benbender** [comment] 2020-10-09 10:18
Another Idea: It would be also nice to have the option to simply force the use of a specific backlight-implementation via boot-arg. That would be even simpler I think as to redo the cpu-detection?

Use case: 5917 is troublesome on Hackintoshes in different ways and until now the backlight never worked with CFL-framebuffers. One could start experimenting if the backlight could be simply fixed with this kext.

**Comment by hieplpvip** [comment] 2020-10-09 13:02
I don't think it's necessary. The only case that it's useful is UHD620, which can be solved easily with a CPUID check.

**Comment by hieplpvip** [comment] 2020-10-09 14:23
@benbender Can you test this? No need to use `lilucpu=9`. In addition, backlight should also work with CFL framebuffer.

[AppleBacklightSmoother-1.0.1-DEBUG.zip](https://github.com/hieplpvip/AppleBacklightSmoother/files/5355523/AppleBacklightSmoother-1.0.1-DEBUG.zip)

**Comment by benbender** [comment] 2020-10-09 16:22
Seems to be working. Thank you very much!

**Closed as completed** 2020-10-09 16:38 UTC
