### ISSUE TITLE
Display does not turn completely black on lowest brightness-setting

### ISSUE THREAD

**Issue by benbender** [hieplpvip/AppleBacklightSmoother#8] opened 2020-10-28 11:00 UTC
Hey,

I just noticed that the display of my Thinkpad T480, KabyLake-R, iGPU-pciId 5918, doesnt turn completely black on lowest brightness-setting as it normally would. Would be nice to get it fixed as I'm often turning my screen down to listen to podcasts :)

Thanks again for your work!

Best

**Comment by Ubsefor** [comment] 2020-11-13 07:14
Duplicate of #6

**Closed as completed** 2020-11-13 11:58 UTC
